AWSTemplateFormatVersion: "2010-09-09"
Description: Logistics Warehouse PostgreSQL RDS

Parameters:
  EnvironmentName:
    Type: String
    Default: production
  VpcId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnet1Id:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2Id:
    Type: AWS::EC2::Subnet::Id
  DatabasePassword:
    Type: String
    NoEcho: true
  DatabaseName:
    Type: String
    Default: logistics
  DatabaseUsername:
    Type: String
    Default: logistics_admin

Resources:
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: PostgreSQL security group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.20.0.0/16
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Logistics PostgreSQL subnet group
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id

  Database:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBInstanceClass: db.t3.micro
      Engine: postgres
      EngineVersion: "16"
      AllocatedStorage: "20"
      StorageType: gp3
      DBName: !Ref DatabaseName
      MasterUsername: !Ref DatabaseUsername
      MasterUserPassword: !Ref DatabasePassword
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup
      PubliclyAccessible: false
      BackupRetentionPeriod: 7
      MultiAZ: false

Outputs:
  DatabaseEndpoint:
    Value: !GetAtt Database.Endpoint.Address
  DatabasePort:
    Value: !GetAtt Database.Endpoint.Port
  DatabaseName:
    Value: !Ref DatabaseName
  DatabaseUsername:
    Value: !Ref DatabaseUsername
