---
- name: Install Docker
  ansible.builtin.package:
    name: docker
    state: present

- name: Enable Docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Add ec2-user to docker group
  ansible.builtin.user:
    name: ec2-user
    groups: docker
    append: true
